/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfind;

import com.drew.imaging.FileType;
import com.drew.imaging.FileTypeDetector;
import com.drew.imaging.ImageMetadataReader;
import static com.drew.imaging.ImageMetadataReader.readMetadata;
import com.drew.metadata.Directory;
import com.drew.metadata.Metadata;
import com.drew.metadata.Tag;
import com.drew.metadata.exif.ExifDirectoryBase;
import com.drew.metadata.exif.ExifSubIFDDirectory;
import com.drew.metadata.exif.GpsDirectory;
import com.sun.jna.ptr.IntByReference;
import datalog.coord.PointSimple;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import libraw.LibRaw;
import libraw.LibRawData;
import libraw.libraw_processed_image_t;
import org.apache.commons.io.FileSystemUtils;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author tophe
 */
public class JFind2 extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form JFind2
     */
    public JFind2() {
        try {
            String metal = "javax.swing.plaf.metal.MetalLookAndFeel";
            String synth = "javax.swing.plaf.synth.SynthLookAndFeel"; // --> since JDK-1.5

            String gtk = "com.sun.java.swing.plaf.gtk.GTKLookAndFeel"; // -> since JDK-1.4

            String motif = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
            String windows = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";

            String os = System.getProperty("os.name");
            if (os.startsWith("Linux")) {
                try // Install client system look and feel.
                {
                    UIManager.setLookAndFeel(metal);
                } catch (Exception e) {
                }
            } else {
                try // Install client system look and feel.
                {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        preInit();
        initComponents();
        postInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        fPatternPanel = new javax.swing.JPanel();
        fPatternLabel = new javax.swing.JLabel();
        fPatternField = new javax.swing.JTextField();
        searchInPanel = new javax.swing.JPanel();
        searchInLabel = new javax.swing.JLabel();
        searchInField = new javax.swing.JTextField();
        searchInButton = new javax.swing.JButton();
        copyInPanel = new javax.swing.JPanel();
        copyInLabel = new javax.swing.JLabel();
        copyInField = new javax.swing.JTextField();
        copyInButton = new javax.swing.JButton();
        copyInFreeSpaceLabel = new javax.swing.JLabel();
        cpiMbLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        optDirComboBox = new javax.swing.JComboBox();
        copyRadioButton = new javax.swing.JRadioButton();
        moveRadioButton = new javax.swing.JRadioButton();
        wptExport = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        topJSplitPane = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        imgPanel = new jfind.jpegPanel();
        imgInfosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        exifInfos = new javax.swing.JTextArea();
        bottomJSplitPane = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        goodScrollPane = new javax.swing.JScrollPane();
        goodList = new javax.swing.JList<>();
        nbGoodLabel = new javax.swing.JLabel();
        goodListNumber = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        matchButLabel = new javax.swing.JLabel();
        badScrollPane = new javax.swing.JScrollPane();
        badList = new javax.swing.JList<>();
        badListNumber = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTree = new javax.swing.JTree();
        resultTree.setModel(resultTreeModel);
        resultTree.setCellRenderer(new ResultNodeRenderer());
        resultTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {

            public void valueChanged(javax.swing.event.TreeSelectionEvent event) {
                Object o = event.getNewLeadSelectionPath().getLastPathComponent();
                FileInfos fi = null;

                if (o instanceof ResultNode) {
                    fi = ((ResultNode) o).getFileInfos();
                } else {
                    fi = ((DoublonNode) o).getFileInfos();
                }

                goodList.setSelectedValue(fi, true);
                updateJpgPanel(fi.getAbsolutePath());

            }
        });
        showSearchLabel = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jPanel1.add(ImagePanel);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchPanel.setBackground(new java.awt.Color(204, 255, 204));
        searchPanel.setMaximumSize(new java.awt.Dimension(50, 50));
        searchPanel.setMinimumSize(new java.awt.Dimension(50, 50));
        searchPanel.setPreferredSize(new java.awt.Dimension(400, 296));

        fPatternPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fPatternLabel.setText("Files pattern:");

        fPatternField.setText("*.(jpg|RW2)");

        javax.swing.GroupLayout fPatternPanelLayout = new javax.swing.GroupLayout(fPatternPanel);
        fPatternPanel.setLayout(fPatternPanelLayout);
        fPatternPanelLayout.setHorizontalGroup(
            fPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPatternPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fPatternLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fPatternField)
                .addGap(6, 6, 6))
        );
        fPatternPanelLayout.setVerticalGroup(
            fPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fPatternLabel)
                .addComponent(fPatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchInPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchInLabel.setText("Search path:");

        searchInField.setText("/home/tophe/CG/Perso/Photos/incoming/");
        searchInField.setToolTipText("");

        searchInButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        searchInButton.setText("select ...");
        searchInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchInPanelLayout = new javax.swing.GroupLayout(searchInPanel);
        searchInPanel.setLayout(searchInPanelLayout);
        searchInPanelLayout.setHorizontalGroup(
            searchInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchInField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchInPanelLayout.setVerticalGroup(
            searchInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(searchInLabel)
                .addComponent(searchInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchInButton))
        );

        copyInPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        copyInLabel.setText("Copy in:");

        copyInField.setText("/tmp/JFind");

        copyInButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        copyInButton.setText("select ...");
        copyInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyInButtonActionPerformed(evt);
            }
        });

        copyInFreeSpaceLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        copyInFreeSpaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copyInFreeSpaceLabel.setText("-");

        cpiMbLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cpiMbLabel.setText("Mb available");

        javax.swing.GroupLayout copyInPanelLayout = new javax.swing.GroupLayout(copyInPanel);
        copyInPanel.setLayout(copyInPanelLayout);
        copyInPanelLayout.setHorizontalGroup(
            copyInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copyInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copyInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(copyInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(copyInPanelLayout.createSequentialGroup()
                        .addComponent(copyInField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyInButton))
                    .addGroup(copyInPanelLayout.createSequentialGroup()
                        .addComponent(copyInFreeSpaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpiMbLabel)))
                .addContainerGap())
        );
        copyInPanelLayout.setVerticalGroup(
            copyInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copyInPanelLayout.createSequentialGroup()
                .addGroup(copyInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(copyInLabel)
                    .addComponent(copyInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyInButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(copyInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyInFreeSpaceLabel)
                    .addComponent(cpiMbLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Subfolder pattern");

        optDirComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Année/Mois/Jour", "Année/Mois", "Année", "none" }));
        optDirComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDirComboBoxActionPerformed(evt);
            }
        });

        copyRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        copyRadioButton.setSelected(true);
        copyRadioButton.setText("copie des fichiers sources");
        copyRadioButton.setToolTipText("");
        copyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyRadioButtonActionPerformed(evt);
            }
        });

        moveRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        moveRadioButton.setText("déplacement des fichiers source");
        moveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(optDirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyRadioButton)
                            .addComponent(moveRadioButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optDirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wptExport.setText("Wpt Export");
        wptExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wptExportActionPerformed(evt);
            }
        });

        goButton.setText("Copy");
        goButton.setToolTipText("");
        goButton.setEnabled(false);
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fPatternPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wptExport)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fPatternPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wptExport)
                    .addComponent(goButton)
                    .addComponent(searchButton))
                .addContainerGap())
        );

        topJSplitPane.setDividerLocation(400);
        topJSplitPane.setMinimumSize(new java.awt.Dimension(800, 600));
        topJSplitPane.setPreferredSize(new java.awt.Dimension(0, 0));

        imgPanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                imgPanelAncestorResized(evt);
            }
        });
        imgPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                imgPanelPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(imgPanel);

        topJSplitPane.setLeftComponent(jScrollPane3);

        imgInfosPanel.setBackground(new java.awt.Color(255, 204, 153));

        exifInfos.setColumns(20);
        exifInfos.setRows(5);
        jScrollPane2.setViewportView(exifInfos);

        javax.swing.GroupLayout imgInfosPanelLayout = new javax.swing.GroupLayout(imgInfosPanel);
        imgInfosPanel.setLayout(imgInfosPanelLayout);
        imgInfosPanelLayout.setHorizontalGroup(
            imgInfosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgInfosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        imgInfosPanelLayout.setVerticalGroup(
            imgInfosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgInfosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        topJSplitPane.setRightComponent(imgInfosPanel);

        bottomJSplitPane.setDividerLocation(600);

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        goodList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        goodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        goodList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                goodListValueChanged(evt);
            }
        });
        goodScrollPane.setViewportView(goodList);

        nbGoodLabel.setText("Files found:");

        goodListNumber.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        goodListNumber.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(nbGoodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goodListNumber)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(goodScrollPane)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbGoodLabel)
                    .addComponent(goodListNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goodScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel7);

        matchButLabel.setText("Founds but have issue (exif, format, ...):");

        badList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        badList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        badScrollPane.setViewportView(badList);

        badListNumber.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        badListNumber.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchButLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badListNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(badScrollPane)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchButLabel)
                    .addComponent(badListNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        bottomJSplitPane.setLeftComponent(jPanel6);

        resultTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                resultTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(resultTree);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        bottomJSplitPane.setRightComponent(jPanel10);

        showSearchLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
            .addComponent(topJSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bottomJSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topJSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(showSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(579, Short.MAX_VALUE)
                    .addComponent(bottomJSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optDirComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDirComboBoxActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        int i = cb.getSelectedIndex();
        switch (i) {
            case 0:
                yearsDirectory = true;
                monthDirectory = true;
                dayDirectory = true;
                break;
            case 1:
                yearsDirectory = true;
                monthDirectory = true;
                dayDirectory = false;
                break;
            case 2:
                yearsDirectory = true;
                monthDirectory = false;
                dayDirectory = false;
                break;
            case 3:
                yearsDirectory = false;
                monthDirectory = false;
                dayDirectory = false;
                break;
        }
        updateResultTree();    }//GEN-LAST:event_optDirComboBoxActionPerformed

    private void moveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRadioButtonActionPerformed
        goButton.setText("Déplacer");
        copy = false;    }//GEN-LAST:event_moveRadioButtonActionPerformed

    private void copyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyRadioButtonActionPerformed
        goButton.setText("Copier");
        copy = true;                    copy = true;    }//GEN-LAST:event_copyRadioButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        System.out.println("Start"); // TODO

        searching = true;
        go();
        System.out.println("End"); // TODO
    }//GEN-LAST:event_searchButtonActionPerformed

    private void wptExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wptExportActionPerformed
        exportWptFiles(); // TODO Auto-generated Event stub actionPerformed()
    }//GEN-LAST:event_wptExportActionPerformed

    private void resultTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_resultTreeValueChanged
        Object o = evt.getNewLeadSelectionPath().getLastPathComponent();
        FileInfos fi = null;

        if (o instanceof ResultNode) {
            fi = ((ResultNode) o).getFileInfos();
        } else {
            fi = ((DoublonNode) o).getFileInfos();
        }

        goodList.setSelectedValue(fi, true);
        updateJpgPanel(fi.getAbsolutePath());
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTreeValueChanged

    private void searchInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInButtonActionPerformed
        int ret = fc.showOpenDialog(JFind2.this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            searchInField.setText(fc.getSelectedFile().getPath());
            fSearchIn = new File(searchInField.getText());
        }
    }//GEN-LAST:event_searchInButtonActionPerformed

    private void copyInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyInButtonActionPerformed
        int ret = fc.showOpenDialog(JFind2.this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            copyInField.setText(fc.getSelectedFile().getPath());
            fCopyIn = new File(copyInField.getText());
            try {
                long freeSpace = FileSystemUtils.freeSpaceKb(copyInField.getText());
                freeSpace = freeSpace / 1024;
                copyInFreeSpaceLabel.setText(String.valueOf(freeSpace));
                ResultNode racine = (ResultNode) resultTreeModel.getRoot();
                racine.setNode(copyInField.getText());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
     }//GEN-LAST:event_copyInButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if (copy) {
            copyJpegFiles();
        } else {
            moveJpegFiles();
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void goodListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_goodListValueChanged
        // TODO add your handling code here:

        JList gl = (JList) evt.getSource();

        int firstIndex = evt.getFirstIndex();
        int lastIndex = evt.getLastIndex();
        boolean isAdjusting = evt.getValueIsAdjusting();

        if (isAdjusting) {
            Object o = gl.getModel().getElementAt(lastIndex);
            FileInfos fi = (FileInfos) o;
            // Need to select in destination tree
            updateJpgPanel(fi.getAbsolutePath());

            //System.out.println(o.toString());
        }
    }//GEN-LAST:event_goodListValueChanged

    private void imgPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_imgPanelPropertyChange
        // TODO add your handling code here:
        System.out.println("imgPanelPropertyChange");
    }//GEN-LAST:event_imgPanelPropertyChange

    private void imgPanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_imgPanelAncestorResized
        // TODO add your handling code here:
        imgPanel.revalidate();
        imgPanel.repaint();
    }//GEN-LAST:event_imgPanelAncestorResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFind2 jf = new JFind2();
                jf.setDefaultCloseOperation(EXIT_ON_CLOSE);
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JList<String> badList;
    private javax.swing.JLabel badListNumber;
    private javax.swing.JScrollPane badScrollPane;
    private javax.swing.JSplitPane bottomJSplitPane;
    private javax.swing.JButton copyInButton;
    private javax.swing.JTextField copyInField;
    private javax.swing.JLabel copyInFreeSpaceLabel;
    private javax.swing.JLabel copyInLabel;
    private javax.swing.JPanel copyInPanel;
    private javax.swing.JRadioButton copyRadioButton;
    private javax.swing.JLabel cpiMbLabel;
    private javax.swing.JTextArea exifInfos;
    private javax.swing.JTextField fPatternField;
    private javax.swing.JLabel fPatternLabel;
    private javax.swing.JPanel fPatternPanel;
    private javax.swing.JButton goButton;
    private javax.swing.JList<String> goodList;
    private javax.swing.JLabel goodListNumber;
    private javax.swing.JScrollPane goodScrollPane;
    private javax.swing.JPanel imgInfosPanel;
    private jfind.jpegPanel imgPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel matchButLabel;
    private javax.swing.JRadioButton moveRadioButton;
    private javax.swing.JLabel nbGoodLabel;
    private javax.swing.JComboBox<String> optDirComboBox;
    private javax.swing.JTree resultTree;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchInButton;
    private javax.swing.JTextField searchInField;
    private javax.swing.JLabel searchInLabel;
    private javax.swing.JPanel searchInPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel showSearchLabel;
    private javax.swing.JSplitPane topJSplitPane;
    private javax.swing.JButton wptExport;
    // End of variables declaration//GEN-END:variables

    private ButtonGroup moveCopyButtonGroup = null;

    private File fSearchIn;
    private File fCopyIn;
    private JFileChooser fc = new JFileChooser();
    private boolean yearsDirectory = true;
    private boolean monthDirectory = true;
    private boolean dayDirectory = false;
    private boolean searching = false;
    private int nbGoodList = 0;
    private long sizeGoodList = 0;
    private boolean copy = true;
    private DefaultListModel goodDList = new DefaultListModel();
    private DefaultListModel badDList = new DefaultListModel();
    private int nbBadList = 0;
    private DefaultTreeModel resultTreeModel = null;
    private BufferedImage jpgImg;

    Hashtable<String, Integer> imageIOAvailableFormats = new Hashtable<String, Integer>();
    private LibRaw libRaw = null;
    private LibRawData libRawDatas = null;

    private void go() {
//		go(new File( searchInField.getText()), convert(fPatternField.getText()));

        new Thread(this).start();
    }

    private void go(File root, String pattern) {
        String[] fileList = root.list();
        DefaultMutableTreeNode racine = (DefaultMutableTreeNode) resultTreeModel.getRoot();

        racine.removeAllChildren();
        goodDList.removeAllElements();
        nbGoodList = 0;
        sizeGoodList = 0;
        badDList.removeAllElements();
        nbBadList = 0;
        resultTreeModel.reload();

        if (fileList != null) {
            Pattern p;
            p = Pattern.compile(pattern, Pattern.CASE_INSENSITIVE);
            checkForFile(root.getAbsolutePath(), p, fileList);
        }
    }

    public void run() {
        searchButton.setEnabled(false);
        go(new File(searchInField.getText()), convert(fPatternField.getText()));
        searchButton.setEnabled(true);
    }

    private void preInit() {

        System.out.println("ImlageIO available formats");
        for (String fn : ImageIO.getReaderFormatNames()) {
            fn = fn.toLowerCase();
            if (!imageIOAvailableFormats.containsKey(fn)) {
                imageIOAvailableFormats.put(fn, 1);
                System.out.println("  - " + fn);
            } else {
                imageIOAvailableFormats.replace(fn, imageIOAvailableFormats.get(fn) + 1);
            }
        }
        libRaw = LibRaw.INSTANCE;
        libRawDatas = libRaw.libraw_init(0);

        // Some init have to be done before components creation (initComponents())
        resultTreeModel = new DefaultTreeModel(new ResultNode("root"));
    }

    private void postInit() {
        // Some init have to be done after components creation (initComponents())
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        goodList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        goodList.setModel(goodDList);

        badList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        badList.setModel(badDList);

        moveCopyButtonGroup = new ButtonGroup();
        moveCopyButtonGroup.add(copyRadioButton);
        moveCopyButtonGroup.add(moveRadioButton);

        Dimension dsp = topJSplitPane.getParent().getSize();
        topJSplitPane.setDividerLocation((int) ((3 * dsp.width) / 4));

        dsp = bottomJSplitPane.getParent().getSize();
        bottomJSplitPane.setDividerLocation((int) (dsp.width / 4));
    }

    private void updateResultTree() {
        DefaultMutableTreeNode racine = (DefaultMutableTreeNode) resultTreeModel.getRoot();
        racine.removeAllChildren();
        resultTreeModel.reload();
        Enumeration e = goodDList.elements();

        while (e.hasMoreElements()) {
            FileInfos fi = (FileInfos) e.nextElement();
            updateResultTree(fi);
        }

    }

    private void updateResultTree(FileInfos fi) {
        DefaultMutableTreeNode racine = (DefaultMutableTreeNode) resultTreeModel.getRoot();
        ResultNode rn = null, tmpNode = null, parentNode = null,
                yearNode = null, monthNode = null, dayNode = null;
        boolean found = false;

        parentNode = (ResultNode) racine;

        if (yearsDirectory) {
            String y = String.valueOf(fi.getYear());
            Enumeration e = racine.children();
            while (e.hasMoreElements()) {
                rn = (ResultNode) e.nextElement();
                if (y.equals(rn.toString())) {
                    found = true;
                    break;
                }
            }

            if (!found) {
                tmpNode = new ResultNode(y, parentNode);
                racine.add(tmpNode);
                rn = tmpNode;
            }

            yearNode = rn;
            parentNode = yearNode;

            if (monthDirectory) {
                found = false;
                String m = fi.getMonth() < 10 ? "0" + String.valueOf(fi.getMonth()) : String.valueOf(fi.getMonth());
                e = yearNode.children();
                while (e.hasMoreElements()) {
                    rn = (ResultNode) e.nextElement();
                    if (m.equals(rn.toString())) {
                        found = true;
                        break;
                    }
                }

                if (!found) {
                    tmpNode = new ResultNode(m, yearNode);
                    yearNode.add(tmpNode);
                    rn = tmpNode;
                }

                monthNode = rn;
                parentNode = monthNode;

                if (dayDirectory) {
                    found = false;
                    String d = (fi.getDay() < 10) ? "0" + String.valueOf(fi.getDay()) : String.valueOf(fi.getDay());
                    e = monthNode.children();
                    while (e.hasMoreElements()) {
                        rn = (ResultNode) e.nextElement();
                        if (d.equals(rn.toString())) {
                            found = true;
                            break;
                        }
                    }

                    if (!found) {
                        tmpNode = new ResultNode(d, monthNode);
                        monthNode.add(tmpNode);
                        dayNode = tmpNode;
                    } else {
                        dayNode = rn;
                    }

                    parentNode = dayNode;
                }
            }
        }

        found = false;
        rn = null;
        Enumeration e = parentNode.children();
        while (e.hasMoreElements()) {
            rn = (ResultNode) e.nextElement();
            if (fi.getNewNameWithExtension().equals(rn.toString())) {
                found = true;
                break;
            }
        }

        if ((!found) || (rn == null)) {
            parentNode.add(new ResultNode(fi.getNewNameWithExtension(), false, fi, parentNode));
        } else {
            DoublonNode dn1 = null, dn2 = null;

            if (rn.isLeaf()) {
                dn1 = new DoublonNode((FileInfos) rn.getFileInfosList().get(0), rn); //+" ("+rn.getFileInfos().getSize()+")")

                rn.add(dn1);
            }
            dn2 = new DoublonNode(fi, rn);
            rn.add(dn2); //+" ("+fi.getSize()+")"));

            rn.addFileInfos(fi);
            if (dn1 != null) {
                dn1.updateExistInfo();
            }
            dn2.updateExistInfo();
        }
        resultTreeModel.reload();

        // Expand row if node
        e = ((DefaultMutableTreeNode) resultTree.getModel().getRoot()).preorderEnumeration();
        if (null != e) {
            while (e.hasMoreElements()) {
                Object o = e.nextElement();
                if (o instanceof ResultNode) {
                    rn = (ResultNode) o;
                    if (!rn.isLeaf()) {
                        resultTree.expandPath(new TreePath(rn.getPath()));
                    }
                }
            }
        }
    }

    private void checkForFile(String rootDir, Pattern p, String[] fileList) {
        if (null != fileList) {
            for (int i = 0; i < fileList.length; i++) {
                File f = new File(rootDir, fileList[i]);

                if (f.isDirectory()) {
                    String ap = f.getAbsolutePath();
                    String path = f.getPath();

                    showSearchLabel.setText(ap);
                    checkForFile(path, p, f.list());
                } else {
                    Matcher m = p.matcher(f.getName());
                    if (m.matches()) {
                        FileInfos fi = null;
                        String ap = f.getAbsolutePath();
                        try {
                            showSearchLabel.setText(ap);

                            System.out.format("[[%s]]\n", f.getName());

                            Metadata metadata = ImageMetadataReader.readMetadata(f);

                            for (Directory directory : metadata.getDirectories()) {
                                for (Tag tag : directory.getTags()) {
                                    if (tag.getTagName().contentEquals("Date/Time Digitized") && (!(directory instanceof ExifSubIFDDirectory))) {
                                        System.out.format(" - %s \n", directory.getClass().toString());
                                        System.out.format("  [%s] - %s = %s\n",
                                                directory.getName(), tag.getTagName(), tag.getDescription());
                                    }
                                }
                                if (directory.hasErrors()) {
                                    for (String error : directory.getErrors()) {
                                        System.err.format("ERROR: %s", error);
                                    }
                                }
                            }

                            if (metadata != null) {
                                Directory d = metadata.getFirstDirectoryOfType(ExifSubIFDDirectory.class);
                                if (d != null) {
                                    String dt = d.getDescription(ExifSubIFDDirectory.TAG_DATETIME_DIGITIZED);
                                    if (dt != null) {
                                        fi = new FileInfos(f.getAbsolutePath(), f.length(), true, true, dt);
                                        goodDList.addElement(fi);
                                        nbGoodList++;
                                        sizeGoodList += f.length();
                                        goodListNumber.setText(String.valueOf(nbGoodList) + " (" + String.valueOf(sizeGoodList / 1048576) + " Mb)");
                                        updateResultTree(fi);
                                    } else {
                                        fi = new FileInfos(f.getAbsolutePath(), f.length(), true, false, dt);
                                        badDList.addElement(fi);
                                        nbBadList++;
                                        badListNumber.setText(String.valueOf(nbBadList));
                                    }
                                } else {
                                    fi = new FileInfos(f.getAbsolutePath());
                                    badDList.addElement(fi);
                                    nbBadList++;
                                    badListNumber.setText(String.valueOf(nbBadList));
                                }
                            } else {
                                fi = new FileInfos(f.getAbsolutePath());
                                badDList.addElement(fi);
                                nbBadList++;
                                badListNumber.setText(String.valueOf(nbBadList));
                            }

                        } catch (Exception e) {
                            if (e.getMessage().compareTo("not a jpeg file") == 0) {
                                fi = new FileInfos(f.getAbsolutePath());
                                badDList.addElement(fi);
                                nbBadList++;
                                goodListNumber.setText(String.valueOf(nbGoodList));
                            } else {
                                e.printStackTrace();
                            }

                        }
                    }
                }
            }

            showSearchLabel.setText("");

            StringBuffer copyInSizeString = new StringBuffer(copyInFreeSpaceLabel.getText());
            if (!"-".contentEquals(copyInSizeString)) {
                long copyInSize = Long.parseLong(copyInSizeString.toString());
                if (goodDList.size() > 0 && ((sizeGoodList / 1048576) < copyInSize)) {
                    goButton.setEnabled(true);
                }
            }
        }
    }

    private void copyJpegFiles() {
        String CopyInDir = copyInField.getText();
        File rootDir = new File(CopyInDir);

        Object o = null;
        ResultNode rn = null;
        Enumeration e = ((DefaultMutableTreeNode) resultTree.getModel().getRoot()).preorderEnumeration();

        while (e.hasMoreElements()) {
            o = e.nextElement();

            if (o instanceof ResultNode) {
                rn = (ResultNode) o;
                if ((!rn.isLeaf()) && (rn.isDir())) {
                    TreeNode tn[] = rn.getPath();
                    String fp = ((ResultNode) tn[0]).toString();

                    for (int i = 1; i < tn.length; i++) {
                        fp = fp + File.separator + ((ResultNode) tn[i]).toString();
                    }

                    File dir = new File(fp);
                    if (dir.exists()) {
                        if (!dir.isDirectory()) {
                            // Lancer une exception
                        }
                    } else {
                        dir.mkdir();
                    }
                } else // 
                {
                    if (rn.isLeaf() && (rn.getFileInfosList().size() == 1)) {
                        if (!rn.exist()) {
                            File sf = new File(rn.getFileInfos().getAbsolutePath());
                            File df = new File(rn.getTreeFilePath());

                            try {
                                FileUtils.copyFile(sf, df);
                            } catch (Exception exp) {
                                exp.printStackTrace();
                            }
                        }
                    }
                }
            } else {
                DoublonNode dn = (DoublonNode) o;
                // It's not a ResultNode 
                if (dn.haveSameSize) {
                    // Suivant les options suppprimer le fichier source
                } else if (!dn.exist()) {
                    File sf = new File(dn.getFileInfos().getAbsolutePath());
                    File df = new File(dn.getTreeFilePath());
                    try {
                        FileUtils.copyFile(sf, df);
                    } catch (Exception exp) {
                        exp.printStackTrace();
                    }
                }
            }

        }
    }

    private void moveJpegFiles() {
        String CopyInDir = copyInField.getText();
        File rootDir = new File(CopyInDir);

        Object o = null;
        ResultNode rn = null;
        Enumeration e = ((DefaultMutableTreeNode) resultTree.getModel().getRoot()).preorderEnumeration();

        while (e.hasMoreElements()) {
            o = e.nextElement();

            if (o instanceof ResultNode) {
                rn = (ResultNode) o;
                if ((!rn.isLeaf()) && (rn.isDir())) {
                    String fp = rn.getTreeFilePath();
                    File dir = new File(fp);
                    if (dir.exists()) {
                        if (!dir.isDirectory()) {
                            // Lancer une exception
                        }
                    } else {
                        dir.mkdir();
                    }
                } else // 
                {
                    if (rn.isLeaf() && (rn.getFileInfosList().size() == 1)) {
                        if (!rn.exist()) {
                            File sf = new File(rn.getFileInfos().getAbsolutePath());
                            File df = new File(rn.getTreeFilePath());

                            try {
                                if (!sf.renameTo(df)) {
                                    int toto = 0;
                                }
                            } catch (Exception exp) {
                                exp.printStackTrace();
                            }
                        }
                    }
                }
            } else {
                DoublonNode dn = (DoublonNode) o;
                // It's not a ResultNode 
                if (dn.haveSameSize) {
                    // Suivant les options suppprimer le fichier source
                } else if (!dn.exist()) {
                    File sf = new File(dn.getFileInfos().getAbsolutePath());
                    File df = new File(dn.getTreeFilePath());
                    if (!sf.renameTo(df)) {
                        int toto = 0;
                    }
                }
            }

        }
    }

    private String convert(String fileName) {
        String convertedFileName = "";

        for (int i = 0; i < fileName.length(); i++) {
            char ch = fileName.charAt(i);
            switch (ch) {
                case '*':
                    convertedFileName += "(.*)";
                    break;
                case '?':
                    convertedFileName += "(.)";
                    break;
                case '.':
                    convertedFileName += "\\.";
                    break;
                default:
                    convertedFileName += ch;
            }
        }

        /*
         * The caret matches the beginning of a string.
         * The dollar sign matches the end of a string.
         */
        return "^" + convertedFileName + "$";
    }

    private void exportWptFiles() {
        JFindGpsLog l = new JFindGpsLog(null, null);
        String CopyInDir = copyInField.getText();
        File rootDir = new File(CopyInDir);

        Object o = null;
        ResultNode rn = null;
        Enumeration e = ((DefaultMutableTreeNode) resultTree.getModel().getRoot()).preorderEnumeration();

        while (e.hasMoreElements()) {
            o = e.nextElement();

            if (o instanceof ResultNode) {
                rn = (ResultNode) o;
                if ((!rn.isLeaf()) && (rn.isDir())) {
                } else // 
                {
                    if (rn.isLeaf() && (rn.getFileInfosList().size() == 1)) {
                        if (!rn.exist()) {
                            File sf = new File(rn.getFileInfos().getAbsolutePath());
                            try {
                                Metadata metadata = ImageMetadataReader.readMetadata(sf);
                                Directory d = metadata.getFirstDirectoryOfType(ExifDirectoryBase.class);
                                //                               Iterator tags = d.getTagIterator();
//                                System.out.println(sf.getName());
//
//                                HashMap map = ((GpsDirectory) d).getTagNameMap();
//                                while (tags.hasNext()) {
//                                    Tag tag = (Tag) tags.next();
//                                    System.out.println(tag.toString());
//                                }
                                JFindPointGps pt = JFindGpsDescriptor.getPointGps((GpsDirectory) d);
                                l.addPoint(pt);
                                System.out.println(pt.toString() + "\n----");
                            } catch (Exception exp) {
                                exp.printStackTrace();
                            }

                        }
                    }
                }
            } else {
                DoublonNode dn = (DoublonNode) o;
                // It's not a ResultNode 
                if (dn.haveSameSize) {
                    // Suivant les options suppprimer le fichier source
                } else if (!dn.exist()) {
                }
            }

        }

        //     Collections.sort( l.getList(), ((Comparator)new ComparePointGPSByDate()));
        try {
            JFindDxfExport jfDxf = new JFindDxfExport("test.dxf", l);
            jfDxf.writeDxf();
        } catch (Exception exp) {
            exp.printStackTrace();
        }
    }

    private void updateJpgPanel(String fileName) {
        File f = new File(fileName);

        try {
            BufferedInputStream inputStream = new BufferedInputStream(new FileInputStream(f));
            FileType fileType = FileTypeDetector.detectFileType(inputStream);
            if (!fileType.getName().contentEquals(fileType.Unknown.getName())) {
                Metadata metadata = readMetadata(inputStream, f.length(), fileType);

                Directory d = metadata.getFirstDirectoryOfType(ExifSubIFDDirectory.class);
                exifInfos.setText(f.length() + " bytes\n");
                if (null != d) {
                    for (Tag tag : d.getTags()) {
                        exifInfos.setText(exifInfos.getText() + "\n" + tag.toString());
                    }
                }
                d = metadata.getFirstDirectoryOfType(GpsDirectory.class);
                if (null != d) {
                    for (Tag tag : d.getTags()) {
                        exifInfos.setText(exifInfos.getText() + "\n" + tag.toString());
                    }
                }
                exifInfos.moveCaretPosition(0);

                if (imageIOAvailableFormats.containsKey(fileType.getName().toLowerCase())) {
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            try {
                                jpgImg = ImageIO.read(f);
                                imgPanel.setImage(jpgImg);
                                imgPanel.revalidate();
                                imgPanel.repaint();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    });
                } else {
                    // No Image IO reader available. Try to get thumbnail using libraw
                    int ret = 0;
                    if ((ret = libRaw.libraw_open_file(libRawDatas, f.getAbsolutePath())) != 0) {
                        System.out.println("Cannot open " + f.getAbsolutePath() + " " + libRaw.libraw_strerror(ret));
                    } else {
                        if ((ret = libRaw.libraw_unpack_thumb(libRawDatas)) != 0) {
                            System.out.println("Cannot unpack_thumb " + f.getAbsolutePath() + " " + libRaw.libraw_strerror(ret));
                        } else {
                            IntByReference r = new IntByReference();
                            libraw_processed_image_t thumb = libRaw.libraw_dcraw_make_mem_thumb(libRawDatas, r);
                            byte[] datas = thumb.getDatas();
                            if (null != datas) {
                                jpgImg = ImageIO.read(new ByteArrayInputStream(datas));
                                imgPanel.setImage(jpgImg);
                                imgPanel.revalidate();
                                imgPanel.repaint();
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private class ComparePointGPSByDate implements Comparator {

        public int compare(Object p1, Object p2) {
            return ((PointSimple) p2).getGCDate().after(((PointSimple) p1).getGCDate()) ? 0 : 1;
        }
    }

}
