/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfind;

import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import javax.swing.SwingUtilities;

/**
 *
 * @author tophe
 */
public class testJpeg extends javax.swing.JFrame {

    private BufferedImage jpgImg;
    private BufferedImage rawImg;

    /**
     * Creates new form testJpeg
     */
    public testJpeg() {
        initComponents();

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                try {
                    imgPanel.setImage(jpgImg);
                    //Graphics g = imgPanel.getGraphics();
                    //g.drawImage(jpgImg, 2, 2, imgPanel.getWidth() - 4, imgPanel.getHeight() - 4, imgPanel);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imgPanel = new jfind.jpegPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imgPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testJpeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testJpeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testJpeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testJpeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        testJpeg tj = new testJpeg();
        try {
            File jpg = new File("/home/tophe/tmp/IMG_20161030_194019.jpg");
            File raw = new File("/home/tophe/DCIM_8Gb/DCIM/107_PANA/P1070824.RW2");
                    
            tj.jpgImg = ImageIO.read(jpg);
            tj.rawImg = ImageIO.read(raw);

            ImageInputStream inJpg = ImageIO.createImageInputStream(jpg);
            ImageInputStream inRaw = ImageIO.createImageInputStream(raw);
                    
            String names[] = ImageIO.getReaderFormatNames();
            Iterator<ImageReader> readers = ImageIO.getImageReaders(inJpg);
            System.out.println("Reader for jpgImg:");
            while (readers.hasNext()) {
                ImageReader reader = readers.next();
                System.out.println("  " + reader.getFormatName());
            }

            readers = ImageIO.getImageReaders(inRaw);
            System.out.println("Reader for rawImg:");
            while (readers.hasNext()) {
                ImageReader reader = readers.next();
                System.out.println("  " + reader.getFormatName());
            }

            System.out.println("All readers:");
            for (int i = 0; i < names.length; ++i) {
                System.out.println("reader " + names[i]);
            }

            names = ImageIO.getWriterFormatNames();
            for (int i = 0; i < names.length; ++i) {
                System.out.println("writer " + names[i]);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testJpeg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jfind.jpegPanel imgPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
