/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfind;

import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;
import libraw.LibRaw;
import libraw.LibRawData;
import libraw.libraw_processed_image_t;

/**
 *
 * @author tophe
 */
public class testRaw extends javax.swing.JFrame {

    private BufferedImage jpgImg;
    private BufferedImage rawImg;

    /**
     * Creates new form testJpeg
     */
    public testRaw() {
        initComponents();

//        SwingUtilities.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    imgPanel.setImage(rawImg);
//                    //Graphics g = imgPanel.getGraphics();
//                    //g.drawImage(jpgImg, 2, 2, imgPanel.getWidth() - 4, imgPanel.getHeight() - 4, imgPanel);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imgPanel = new jfind.jpegPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imgPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testRaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testRaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testRaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testRaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        testRaw tj = new testRaw();
        LibRaw libRaw = null;
        LibRawData libRawDatas = null;

        try {
            File jpg = new File("/home/tophe/tmp/IMG_20161030_194019.jpg");
            File raw = new File("/home/tophe/CG/Perso/Photos/WE_20191005/P1100193.RW2");

            libRaw = LibRaw.INSTANCE;
            libRawDatas = libRaw.libraw_init(0);

            int ret = 0;
            if ((ret = libRaw.libraw_open_file(libRawDatas, raw.getAbsolutePath())) != 0) {
                System.out.println("Cannot open " + raw.getAbsolutePath() + " " + libRaw.libraw_strerror(ret));
            } else {
                if ((ret = libRaw.libraw_unpack_thumb(libRawDatas)) != 0) {
                    System.out.println("Cannot unpack_thumb " + raw.getAbsolutePath() + " " + libRaw.libraw_strerror(ret));
//        libraw_processed_image_t *thumb = RawProcessor.dcraw_make_mem_thumb(&ret);
//        if (thumb)
//        {
//          fprintf(stdout, "Writing thumb: %s\n", av[i]);
//          write_thumb(thumb, av[i]);
//          LibRaw::dcraw_clear_mem(thumb);
//        }
//        else
//          fprintf(stderr, "Cannot unpack thumbnail of %s to memory buffer: %s\n", av[i], libraw_strerror(ret));
//      }
                } else {
                    IntByReference r = new IntByReference();
                    libraw_processed_image_t thumb = libRaw.libraw_dcraw_make_mem_thumb(libRawDatas, r);
                    byte[] datas = thumb.getDatas();
                    if (null != datas) {
                        tj.rawImg = ImageIO.read(new ByteArrayInputStream(datas));
                        tj.imgPanel.setImage(tj.rawImg);
//                        Graphics g = tj.imgPanel.getGraphics();
//                        g.drawImage(tj.rawImg, 2, 2, tj.imgPanel.getWidth() - 4, tj.imgPanel.getHeight() - 4, tj.imgPanel);
                    }
                    libRaw.libraw_dcraw_clear_mem(thumb);
                    String toto = "fait_du_velo";
                }
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jfind.jpegPanel imgPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
